# название
name: Project test & build

# целевые события для запуска
# в данном случае это push и pull_request, в ветку prod
on:
  push:
    branches: master

# выполняемые действия
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    # запускаются по шагам
    # name - название шага
    # в github actions будет выводиться название шага, и процессы
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2.3.1
        with:
          persist-credentials: false

      - name: Install 🔧
        run: npm install

      - name: Run Test 🔨
        run: npm run test

      - name: Build 👷
        run: npm run build

      - name: Deploy 🚀
        uses: andgt.github.io/792499-cat-energy-21/
        with:
          # в значение GITHUB_TOKEN помещается ссылка на ваш секрет в репозитории
          # в данном случае его название KEY
          GITHUB_TOKEN: 61084142fda7f821915f9d645b407dd04fd4ad75
          BRANCH: gh-pages
          FOLDER: public
          CLEAN: true
